name: beta

# Controls when the workflow will run
on:
  push:
    tags: ["beta-v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build_pkid:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.lowercase }}
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: threefoldjimber/pkid
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: image
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: Build and push
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}:beta-${{ github.sha }},${{ env.IMAGE_NAME }}:beta-latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: [ build_pkid ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting configs
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.BETA_KUBE_KEY }} | base64 --decode > ${HOME}/.kube/jimber-beta.key
          echo ${{ secrets.BETA_KUBE_CRT }} | base64 --decode > ${HOME}/.kube/jimber-beta.crt
          echo ${{ secrets.BETA_KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          echo $(ls ${HOME}/.kube)
      - name: Upgrade cluster
        run: |
          helm upgrade --install beta-pkid helm_charts -f helm_charts/values/values-beta.yaml --set global.PKID_IMAGE=threefoldjimber/pkid:beta-${{ github.sha }}  --set global.REDIS_PASSWORD="${{ secrets.BETA_REDIS_PASSWORD }}" --set global.REDIS_URL="redis://:${{secrets.BETA_REDIS_PASSWORD}}@beta-pkid-redis-pkid:6379" -n jimber
